// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payment Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package main

import (
	"log"
	"net/http"

	paymentserver "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	PaymentsAPIService := paymentserver.NewPaymentsAPIService()
	PaymentsAPIController := paymentserver.NewPaymentsAPIController(PaymentsAPIService)

	WebhooksAPIService := paymentserver.NewWebhooksAPIService()
	WebhooksAPIController := paymentserver.NewWebhooksAPIController(WebhooksAPIService)

	router := paymentserver.NewRouter(PaymentsAPIController, WebhooksAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
