// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Catalog Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package main

import (
	"log"
	"net/http"

	catalogserver "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	ProductsAPIService := catalogserver.NewProductsAPIService()
	ProductsAPIController := catalogserver.NewProductsAPIController(ProductsAPIService)

	router := catalogserver.NewRouter(ProductsAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
