// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Auth Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package main

import (
	"log"
	"net/http"

	authserver "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	log.Printf("Server started")

	AuthAPIService := authserver.NewAuthAPIService()
	AuthAPIController := authserver.NewAuthAPIController(AuthAPIService)

	router := authserver.NewRouter(AuthAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
