/*
Payment Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package paymentclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaymentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentRequest{}

// PaymentRequest struct for PaymentRequest
type PaymentRequest struct {
	OrderId string `json:"orderId"`
	Amount Money `json:"amount"`
	PaymentMethodToken string `json:"paymentMethodToken"`
}

type _PaymentRequest PaymentRequest

// NewPaymentRequest instantiates a new PaymentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentRequest(orderId string, amount Money, paymentMethodToken string) *PaymentRequest {
	this := PaymentRequest{}
	this.OrderId = orderId
	this.Amount = amount
	this.PaymentMethodToken = paymentMethodToken
	return &this
}

// NewPaymentRequestWithDefaults instantiates a new PaymentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentRequestWithDefaults() *PaymentRequest {
	this := PaymentRequest{}
	return &this
}

// GetOrderId returns the OrderId field value
func (o *PaymentRequest) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *PaymentRequest) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *PaymentRequest) SetOrderId(v string) {
	o.OrderId = v
}

// GetAmount returns the Amount field value
func (o *PaymentRequest) GetAmount() Money {
	if o == nil {
		var ret Money
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *PaymentRequest) GetAmountOk() (*Money, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *PaymentRequest) SetAmount(v Money) {
	o.Amount = v
}

// GetPaymentMethodToken returns the PaymentMethodToken field value
func (o *PaymentRequest) GetPaymentMethodToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentMethodToken
}

// GetPaymentMethodTokenOk returns a tuple with the PaymentMethodToken field value
// and a boolean to check if the value has been set.
func (o *PaymentRequest) GetPaymentMethodTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentMethodToken, true
}

// SetPaymentMethodToken sets field value
func (o *PaymentRequest) SetPaymentMethodToken(v string) {
	o.PaymentMethodToken = v
}

func (o PaymentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["orderId"] = o.OrderId
	toSerialize["amount"] = o.Amount
	toSerialize["paymentMethodToken"] = o.PaymentMethodToken
	return toSerialize, nil
}

func (o *PaymentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"orderId",
		"amount",
		"paymentMethodToken",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentRequest := _PaymentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaymentRequest)

	if err != nil {
		return err
	}

	*o = PaymentRequest(varPaymentRequest)

	return err
}

type NullablePaymentRequest struct {
	value *PaymentRequest
	isSet bool
}

func (v NullablePaymentRequest) Get() *PaymentRequest {
	return v.value
}

func (v *NullablePaymentRequest) Set(val *PaymentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentRequest(val *PaymentRequest) *NullablePaymentRequest {
	return &NullablePaymentRequest{value: val, isSet: true}
}

func (v NullablePaymentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


