/*
Order Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orderclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrderPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderPage{}

// OrderPage struct for OrderPage
type OrderPage struct {
	Items []Order `json:"items"`
	Pagination Pagination `json:"pagination"`
}

type _OrderPage OrderPage

// NewOrderPage instantiates a new OrderPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderPage(items []Order, pagination Pagination) *OrderPage {
	this := OrderPage{}
	this.Items = items
	this.Pagination = pagination
	return &this
}

// NewOrderPageWithDefaults instantiates a new OrderPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderPageWithDefaults() *OrderPage {
	this := OrderPage{}
	return &this
}

// GetItems returns the Items field value
func (o *OrderPage) GetItems() []Order {
	if o == nil {
		var ret []Order
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *OrderPage) GetItemsOk() ([]Order, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *OrderPage) SetItems(v []Order) {
	o.Items = v
}

// GetPagination returns the Pagination field value
func (o *OrderPage) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *OrderPage) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *OrderPage) SetPagination(v Pagination) {
	o.Pagination = v
}

func (o OrderPage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *OrderPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderPage := _OrderPage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrderPage)

	if err != nil {
		return err
	}

	*o = OrderPage(varOrderPage)

	return err
}

type NullableOrderPage struct {
	value *OrderPage
	isSet bool
}

func (v NullableOrderPage) Get() *OrderPage {
	return v.value
}

func (v *NullableOrderPage) Set(val *OrderPage) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderPage) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderPage(val *OrderPage) *NullableOrderPage {
	return &NullableOrderPage{value: val, isSet: true}
}

func (v NullableOrderPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


