/*
Order Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orderclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Cart type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Cart{}

// Cart struct for Cart
type Cart struct {
	Items []CartItem `json:"items"`
	Subtotal Money `json:"subtotal"`
}

type _Cart Cart

// NewCart instantiates a new Cart object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCart(items []CartItem, subtotal Money) *Cart {
	this := Cart{}
	this.Items = items
	this.Subtotal = subtotal
	return &this
}

// NewCartWithDefaults instantiates a new Cart object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCartWithDefaults() *Cart {
	this := Cart{}
	return &this
}

// GetItems returns the Items field value
func (o *Cart) GetItems() []CartItem {
	if o == nil {
		var ret []CartItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *Cart) GetItemsOk() ([]CartItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *Cart) SetItems(v []CartItem) {
	o.Items = v
}

// GetSubtotal returns the Subtotal field value
func (o *Cart) GetSubtotal() Money {
	if o == nil {
		var ret Money
		return ret
	}

	return o.Subtotal
}

// GetSubtotalOk returns a tuple with the Subtotal field value
// and a boolean to check if the value has been set.
func (o *Cart) GetSubtotalOk() (*Money, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subtotal, true
}

// SetSubtotal sets field value
func (o *Cart) SetSubtotal(v Money) {
	o.Subtotal = v
}

func (o Cart) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Cart) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["subtotal"] = o.Subtotal
	return toSerialize, nil
}

func (o *Cart) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"subtotal",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCart := _Cart{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCart)

	if err != nil {
		return err
	}

	*o = Cart(varCart)

	return err
}

type NullableCart struct {
	value *Cart
	isSet bool
}

func (v NullableCart) Get() *Cart {
	return v.value
}

func (v *NullableCart) Set(val *Cart) {
	v.value = val
	v.isSet = true
}

func (v NullableCart) IsSet() bool {
	return v.isSet
}

func (v *NullableCart) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCart(val *Cart) *NullableCart {
	return &NullableCart{value: val, isSet: true}
}

func (v NullableCart) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCart) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


