/*
Catalog Service API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package catalogclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductPage{}

// ProductPage struct for ProductPage
type ProductPage struct {
	Items []Product `json:"items"`
	Pagination Pagination `json:"pagination"`
}

type _ProductPage ProductPage

// NewProductPage instantiates a new ProductPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductPage(items []Product, pagination Pagination) *ProductPage {
	this := ProductPage{}
	this.Items = items
	this.Pagination = pagination
	return &this
}

// NewProductPageWithDefaults instantiates a new ProductPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductPageWithDefaults() *ProductPage {
	this := ProductPage{}
	return &this
}

// GetItems returns the Items field value
func (o *ProductPage) GetItems() []Product {
	if o == nil {
		var ret []Product
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ProductPage) GetItemsOk() ([]Product, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ProductPage) SetItems(v []Product) {
	o.Items = v
}

// GetPagination returns the Pagination field value
func (o *ProductPage) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *ProductPage) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *ProductPage) SetPagination(v Pagination) {
	o.Pagination = v
}

func (o ProductPage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *ProductPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductPage := _ProductPage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductPage)

	if err != nil {
		return err
	}

	*o = ProductPage(varProductPage)

	return err
}

type NullableProductPage struct {
	value *ProductPage
	isSet bool
}

func (v NullableProductPage) Get() *ProductPage {
	return v.value
}

func (v *NullableProductPage) Set(val *ProductPage) {
	v.value = val
	v.isSet = true
}

func (v NullableProductPage) IsSet() bool {
	return v.isSet
}

func (v *NullableProductPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductPage(val *ProductPage) *NullableProductPage {
	return &NullableProductPage{value: val, isSet: true}
}

func (v NullableProductPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


