# ============================================================================ #
#                         PNPM Workspace Configuration                         #
# ============================================================================ #
# This file defines the configuration for the pnpm workspace, which is a       #
# package management tool for JavaScript projects.                             #
#                                                                              #
# See: https://pnpm.io/settings                                                #
# ============================================================================ #

minimumReleaseAge: 0

allowBuilds:
  "@openapitools/openapi-generator-cli": true
  "@scarf/scarf": true
  core-js: true
  esbuild: true
  protobufjs: true
  vue-demi: true

packages:
  - tools
