/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.25.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Error;
import org.openapitools.model.LoginRequest;
import org.openapitools.model.RegisterRequest;
import org.openapitools.model.Token;
import org.openapitools.model.User;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-08-28T18:49:17.749917078Z[Etc/UTC]", comments = "Generator version: 7.25.0")
@Validated
@Tag(name = "Auth", description = "Authentication and user profile operations.")
public interface AuthApi {

    String PATH_GET_CURRENT_USER = "/me";
    /**
     * GET /me : Get the authenticated user profile
     *
     * @return Current user (status code 200)
     *         or Missing or invalid credentials (status code 401)
     */
    @Operation(
        operationId = "getCurrentUser",
        summary = "Get the authenticated user profile",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Current user", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = User.class))
            }),
            @ApiResponse(responseCode = "401", description = "Missing or invalid credentials", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = AuthApi.PATH_GET_CURRENT_USER,
        produces = { "application/json" }
    )
    ResponseEntity<User> getCurrentUser(
        
    );


    String PATH_LOGIN = "/login";
    /**
     * POST /login : Authenticate user and issue tokens
     *
     * @param loginRequest  (required)
     * @return Successful authentication (status code 200)
     *         or Missing or invalid credentials (status code 401)
     */
    @Operation(
        operationId = "login",
        summary = "Authenticate user and issue tokens",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful authentication", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Token.class))
            }),
            @ApiResponse(responseCode = "401", description = "Missing or invalid credentials", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthApi.PATH_LOGIN,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Token> login(
        @Parameter(name = "LoginRequest", description = "", required = true) @Valid @RequestBody LoginRequest loginRequest
    );


    String PATH_REGISTER_USER = "/register";
    /**
     * POST /register : Register a new user
     *
     * @param registerRequest  (required)
     * @return User registered (status code 201)
     *         or Resource conflict (status code 409)
     */
    @Operation(
        operationId = "registerUser",
        summary = "Register a new user",
        tags = { "Auth" },
        responses = {
            @ApiResponse(responseCode = "201", description = "User registered", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = User.class))
            }),
            @ApiResponse(responseCode = "409", description = "Resource conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = AuthApi.PATH_REGISTER_USER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<User> registerUser(
        @Parameter(name = "RegisterRequest", description = "", required = true) @Valid @RequestBody RegisterRequest registerRequest
    );

}
