/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.25.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Cart;
import org.openapitools.model.Error;
import org.springframework.lang.Nullable;
import org.openapitools.model.Order;
import org.openapitools.model.OrderPage;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-08-28T18:49:37.862663304Z[Etc/UTC]", comments = "Generator version: 7.25.0")
@Validated
@Tag(name = "Orders", description = "Shopping cart and order lifecycle operations.")
public interface OrdersApi {

    String PATH_CHECKOUT_CART = "/cart";
    /**
     * POST /cart : Convert the current cart into an order
     *
     * @param idempotencyKey  (required)
     * @return Created order (status code 201)
     *         or Resource conflict (status code 409)
     */
    @Operation(
        operationId = "checkoutCart",
        summary = "Convert the current cart into an order",
        tags = { "Orders" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Created order", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Order.class))
            }),
            @ApiResponse(responseCode = "409", description = "Resource conflict", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = OrdersApi.PATH_CHECKOUT_CART,
        produces = { "application/json" }
    )
    ResponseEntity<Order> checkoutCart(
        @NotNull @Size(min = 8) @Parameter(name = "Idempotency-Key", description = "", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "Idempotency-Key", required = true) String idempotencyKey
    );


    String PATH_GET_CART = "/cart";
    /**
     * GET /cart : Get the current shopping cart
     *
     * @return Current cart (status code 200)
     *         or Missing or invalid credentials (status code 401)
     */
    @Operation(
        operationId = "getCart",
        summary = "Get the current shopping cart",
        tags = { "Orders" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Current cart", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Cart.class))
            }),
            @ApiResponse(responseCode = "401", description = "Missing or invalid credentials", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = OrdersApi.PATH_GET_CART,
        produces = { "application/json" }
    )
    ResponseEntity<Cart> getCart(
        
    );


    String PATH_LIST_ORDERS = "/orders";
    /**
     * GET /orders : List orders for the current user
     *
     * @param page  (optional, default to 1)
     * @param limit  (optional, default to 20)
     * @return Order page (status code 200)
     *         or Missing or invalid credentials (status code 401)
     */
    @Operation(
        operationId = "listOrders",
        summary = "List orders for the current user",
        tags = { "Orders" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Order page", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = OrderPage.class))
            }),
            @ApiResponse(responseCode = "401", description = "Missing or invalid credentials", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = OrdersApi.PATH_LIST_ORDERS,
        produces = { "application/json" }
    )
    ResponseEntity<OrderPage> listOrders(
        @Min(value = 1) @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Min(value = 1) @Max(value = 100) @Parameter(name = "limit", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit
    );

}
