/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.25.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Error;
import org.openapitools.model.Payment;
import org.openapitools.model.PaymentRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-08-28T18:49:47.803481906Z[Etc/UTC]", comments = "Generator version: 7.25.0")
@Validated
@Tag(name = "Payments", description = "Payment transaction operations.")
public interface PaymentsApi {

    String PATH_CREATE_PAYMENT = "/payments";
    /**
     * POST /payments : Create a payment for an order
     *
     * @param idempotencyKey  (required)
     * @param paymentRequest  (required)
     * @return Payment created (status code 201)
     *         or Request validation failed (status code 400)
     */
    @Operation(
        operationId = "createPayment",
        summary = "Create a payment for an order",
        tags = { "Payments" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Payment created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Payment.class))
            }),
            @ApiResponse(responseCode = "400", description = "Request validation failed", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "BearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = PaymentsApi.PATH_CREATE_PAYMENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Payment> createPayment(
        @NotNull @Size(min = 8) @Parameter(name = "Idempotency-Key", description = "", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "Idempotency-Key", required = true) String idempotencyKey,
        @Parameter(name = "PaymentRequest", description = "", required = true) @Valid @RequestBody PaymentRequest paymentRequest
    );

}
