/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.25.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Error;
import org.springframework.lang.Nullable;
import org.openapitools.model.ProductPage;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-08-28T18:49:27.794066194Z[Etc/UTC]", comments = "Generator version: 7.25.0")
@Validated
@Tag(name = "Products", description = "Product catalog and inventory status.")
public interface ProductsApi {

    String PATH_LIST_PRODUCTS = "/products";
    /**
     * GET /products : List products
     *
     * @param page  (optional, default to 1)
     * @param limit  (optional, default to 20)
     * @return Product page (status code 200)
     *         or Request validation failed (status code 400)
     */
    @Operation(
        operationId = "listProducts",
        summary = "List products",
        tags = { "Products" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Product page", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ProductPage.class))
            }),
            @ApiResponse(responseCode = "400", description = "Request validation failed", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ProductsApi.PATH_LIST_PRODUCTS,
        produces = { "application/json" }
    )
    ResponseEntity<ProductPage> listProducts(
        @Min(value = 1) @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Min(value = 1) @Max(value = 100) @Parameter(name = "limit", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit
    );

}
