/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.25.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Error;
import org.springframework.lang.Nullable;
import org.openapitools.model.SearchResult;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-08-28T18:49:57.742760755Z[Etc/UTC]", comments = "Generator version: 7.25.0")
@Validated
@Tag(name = "Search", description = "Full-text product search, filtering, and sorting.")
public interface SearchApi {

    String PATH_SEARCH_PRODUCTS = "/products";
    /**
     * GET /products : Search products with filters and sorting
     *
     * @param q  (required)
     * @param page  (optional, default to 1)
     * @param limit  (optional, default to 20)
     * @param category  (optional)
     * @param sort  (optional)
     * @return Search results (status code 200)
     *         or Request validation failed (status code 400)
     */
    @Operation(
        operationId = "searchProducts",
        summary = "Search products with filters and sorting",
        tags = { "Search" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Search results", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = SearchResult.class))
            }),
            @ApiResponse(responseCode = "400", description = "Request validation failed", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = SearchApi.PATH_SEARCH_PRODUCTS,
        produces = { "application/json" }
    )
    ResponseEntity<SearchResult> searchProducts(
        @NotNull @Size(min = 1) @Parameter(name = "q", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "q", required = true) String q,
        @Min(value = 1) @Parameter(name = "page", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "1") Integer page,
        @Min(value = 1) @Max(value = 100) @Parameter(name = "limit", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit,
        @Parameter(name = "category", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "category", required = false) @Nullable String category,
        @Parameter(name = "sort", description = "", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sort", required = false) @Nullable String sort
    );

}
