/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.25.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Error;
import org.openapitools.model.WebhookEvent;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-08-28T18:49:47.803481906Z[Etc/UTC]", comments = "Generator version: 7.25.0")
@Validated
@Tag(name = "Webhooks", description = "Payment provider callback operations.")
public interface WebhooksApi {

    String PATH_RECEIVE_PAYMENT_WEBHOOK = "/webhooks/provider";
    /**
     * POST /webhooks/provider : Receive a payment provider callback
     *
     * @param webhookEvent  (required)
     * @return Webhook accepted (status code 204)
     *         or Request validation failed (status code 400)
     */
    @Operation(
        operationId = "receivePaymentWebhook",
        summary = "Receive a payment provider callback",
        tags = { "Webhooks" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Webhook accepted"),
            @ApiResponse(responseCode = "400", description = "Request validation failed", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = WebhooksApi.PATH_RECEIVE_PAYMENT_WEBHOOK,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<Void> receivePaymentWebhook(
        @Parameter(name = "WebhookEvent", description = "", required = true) @Valid @RequestBody WebhookEvent webhookEvent
    );

}
