/* tslint:disable */
/* eslint-disable */
/**
 * Order Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Cart,
    CartFromJSON,
    CartToJSON,
} from '../models/Cart';
import {
    type Order,
    OrderFromJSON,
    OrderToJSON,
} from '../models/Order';
import {
    type OrderPage,
    OrderPageFromJSON,
    OrderPageToJSON,
} from '../models/OrderPage';

export interface CheckoutCartRequest {
    /**
     * 
     */
    idempotencyKey: string;
}

export interface ListOrdersRequest {
    /**
     * 
     */
    page?: number;
    /**
     * 
     */
    limit?: number;
}

/**
 * OrdersApi - interface
 * 
 * @export
 * @interface OrdersApiInterface
 */
export interface OrdersApiInterface {
    /**
     * Creates request options for checkoutCart without sending the request
     * @param {string} idempotencyKey 
     * @throws {RequiredError}
     * @memberof OrdersApiInterface
     */
    checkoutCartRequestOpts(requestParameters: CheckoutCartRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Convert the current cart into an order
     * @param {string} idempotencyKey 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApiInterface
     */
    checkoutCartRaw(requestParameters: CheckoutCartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>>;

    /**
     * Convert the current cart into an order
     */
    checkoutCart(requestParameters: CheckoutCartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order>;

    /**
     * Creates request options for getCart without sending the request
     * @throws {RequiredError}
     * @memberof OrdersApiInterface
     */
    getCartRequestOpts(): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get the current shopping cart
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApiInterface
     */
    getCartRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Cart>>;

    /**
     * Get the current shopping cart
     */
    getCart(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Cart>;

    /**
     * Creates request options for listOrders without sending the request
     * @param {number} [page] 
     * @param {number} [limit] 
     * @throws {RequiredError}
     * @memberof OrdersApiInterface
     */
    listOrdersRequestOpts(requestParameters: ListOrdersRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List orders for the current user
     * @param {number} [page] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrdersApiInterface
     */
    listOrdersRaw(requestParameters: ListOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderPage>>;

    /**
     * List orders for the current user
     */
    listOrders(requestParameters: ListOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderPage>;

}

/**
 * 
 */
export class OrdersApi extends runtime.BaseAPI implements OrdersApiInterface {

    /**
     * Creates request options for checkoutCart without sending the request
     */
    async checkoutCartRequestOpts(requestParameters: CheckoutCartRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling checkoutCart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/cart`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Convert the current cart into an order
     */
    async checkoutCartRaw(requestParameters: CheckoutCartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Order>> {
        const requestOptions = await this.checkoutCartRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderFromJSON(jsonValue));
    }

    /**
     * Convert the current cart into an order
     */
    async checkoutCart(requestParameters: CheckoutCartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Order> {
        const response = await this.checkoutCartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCart without sending the request
     */
    async getCartRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/cart`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the current shopping cart
     */
    async getCartRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Cart>> {
        const requestOptions = await this.getCartRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CartFromJSON(jsonValue));
    }

    /**
     * Get the current shopping cart
     */
    async getCart(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Cart> {
        const response = await this.getCartRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listOrders without sending the request
     */
    async listOrdersRequestOpts(requestParameters: ListOrdersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/orders`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List orders for the current user
     */
    async listOrdersRaw(requestParameters: ListOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderPage>> {
        const requestOptions = await this.listOrdersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderPageFromJSON(jsonValue));
    }

    /**
     * List orders for the current user
     */
    async listOrders(requestParameters: ListOrdersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderPage> {
        const response = await this.listOrdersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
