/* tslint:disable */
/* eslint-disable */
/**
 * Payment Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type Payment,
    PaymentFromJSON,
    PaymentToJSON,
} from '../models/Payment';
import {
    type PaymentRequest,
    PaymentRequestFromJSON,
    PaymentRequestToJSON,
} from '../models/PaymentRequest';

export interface CreatePaymentRequest {
    /**
     * 
     */
    idempotencyKey: string;
    /**
     * 
     */
    paymentRequest: PaymentRequest;
}

/**
 * PaymentsApi - interface
 * 
 * @export
 * @interface PaymentsApiInterface
 */
export interface PaymentsApiInterface {
    /**
     * Creates request options for createPayment without sending the request
     * @param {string} idempotencyKey 
     * @param {PaymentRequest} paymentRequest 
     * @throws {RequiredError}
     * @memberof PaymentsApiInterface
     */
    createPaymentRequestOpts(requestParameters: CreatePaymentRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Create a payment for an order
     * @param {string} idempotencyKey 
     * @param {PaymentRequest} paymentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentsApiInterface
     */
    createPaymentRaw(requestParameters: CreatePaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Payment>>;

    /**
     * Create a payment for an order
     */
    createPayment(requestParameters: CreatePaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Payment>;

}

/**
 * 
 */
export class PaymentsApi extends runtime.BaseAPI implements PaymentsApiInterface {

    /**
     * Creates request options for createPayment without sending the request
     */
    async createPaymentRequestOpts(requestParameters: CreatePaymentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['idempotencyKey'] == null) {
            throw new runtime.RequiredError(
                'idempotencyKey',
                'Required parameter "idempotencyKey" was null or undefined when calling createPayment().'
            );
        }

        if (requestParameters['paymentRequest'] == null) {
            throw new runtime.RequiredError(
                'paymentRequest',
                'Required parameter "paymentRequest" was null or undefined when calling createPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/payments`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentRequestToJSON(requestParameters['paymentRequest']),
        };
    }

    /**
     * Create a payment for an order
     */
    async createPaymentRaw(requestParameters: CreatePaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Payment>> {
        const requestOptions = await this.createPaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentFromJSON(jsonValue));
    }

    /**
     * Create a payment for an order
     */
    async createPayment(requestParameters: CreatePaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Payment> {
        const response = await this.createPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
