/* tslint:disable */
/* eslint-disable */
/**
 * Catalog Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ProductPage,
    ProductPageFromJSON,
    ProductPageToJSON,
} from '../models/ProductPage';

export interface ListProductsRequest {
    /**
     * 
     */
    page?: number;
    /**
     * 
     */
    limit?: number;
}

/**
 * ProductsApi - interface
 * 
 * @export
 * @interface ProductsApiInterface
 */
export interface ProductsApiInterface {
    /**
     * Creates request options for listProducts without sending the request
     * @param {number} [page] 
     * @param {number} [limit] 
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    listProductsRequestOpts(requestParameters: ListProductsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List products
     * @param {number} [page] 
     * @param {number} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProductsApiInterface
     */
    listProductsRaw(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductPage>>;

    /**
     * List products
     */
    listProducts(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductPage>;

}

/**
 * 
 */
export class ProductsApi extends runtime.BaseAPI implements ProductsApiInterface {

    /**
     * Creates request options for listProducts without sending the request
     */
    async listProductsRequestOpts(requestParameters: ListProductsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/products`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List products
     */
    async listProductsRaw(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductPage>> {
        const requestOptions = await this.listProductsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductPageFromJSON(jsonValue));
    }

    /**
     * List products
     */
    async listProducts(requestParameters: ListProductsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductPage> {
        const response = await this.listProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
