/* tslint:disable */
/* eslint-disable */
/**
 * Search Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type SearchResult,
    SearchResultFromJSON,
    SearchResultToJSON,
} from '../models/SearchResult';

export interface SearchProductsRequest {
    /**
     * 
     */
    q: string;
    /**
     * 
     */
    page?: number;
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    category?: string;
    /**
     * 
     */
    sort?: SearchProductsSortEnum;
}

/**
 * SearchApi - interface
 * 
 * @export
 * @interface SearchApiInterface
 */
export interface SearchApiInterface {
    /**
     * Creates request options for searchProducts without sending the request
     * @param {string} q 
     * @param {number} [page] 
     * @param {number} [limit] 
     * @param {string} [category] 
     * @param {'relevance' | 'price_asc' | 'price_desc' | 'newest'} [sort] 
     * @throws {RequiredError}
     * @memberof SearchApiInterface
     */
    searchProductsRequestOpts(requestParameters: SearchProductsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Search products with filters and sorting
     * @param {string} q 
     * @param {number} [page] 
     * @param {number} [limit] 
     * @param {string} [category] 
     * @param {'relevance' | 'price_asc' | 'price_desc' | 'newest'} [sort] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApiInterface
     */
    searchProductsRaw(requestParameters: SearchProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchResult>>;

    /**
     * Search products with filters and sorting
     */
    searchProducts(requestParameters: SearchProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchResult>;

}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI implements SearchApiInterface {

    /**
     * Creates request options for searchProducts without sending the request
     */
    async searchProductsRequestOpts(requestParameters: SearchProductsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling searchProducts().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['category'] != null) {
            queryParameters['category'] = requestParameters['category'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/products`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search products with filters and sorting
     */
    async searchProductsRaw(requestParameters: SearchProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchResult>> {
        const requestOptions = await this.searchProductsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchResultFromJSON(jsonValue));
    }

    /**
     * Search products with filters and sorting
     */
    async searchProducts(requestParameters: SearchProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchResult> {
        const response = await this.searchProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const SearchProductsSortEnum = {
    Relevance: 'relevance',
    PriceAsc: 'price_asc',
    PriceDesc: 'price_desc',
    Newest: 'newest',
} as const;
export type SearchProductsSortEnum = typeof SearchProductsSortEnum[keyof typeof SearchProductsSortEnum];
