/* tslint:disable */
/* eslint-disable */
/**
 * Payment Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type WebhookEvent,
    WebhookEventFromJSON,
    WebhookEventToJSON,
} from '../models/WebhookEvent';

export interface ReceivePaymentWebhookRequest {
    /**
     * 
     */
    webhookEvent: WebhookEvent;
}

/**
 * WebhooksApi - interface
 * 
 * @export
 * @interface WebhooksApiInterface
 */
export interface WebhooksApiInterface {
    /**
     * Creates request options for receivePaymentWebhook without sending the request
     * @param {WebhookEvent} webhookEvent 
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    receivePaymentWebhookRequestOpts(requestParameters: ReceivePaymentWebhookRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Receive a payment provider callback
     * @param {WebhookEvent} webhookEvent 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WebhooksApiInterface
     */
    receivePaymentWebhookRaw(requestParameters: ReceivePaymentWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Receive a payment provider callback
     */
    receivePaymentWebhook(requestParameters: ReceivePaymentWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI implements WebhooksApiInterface {

    /**
     * Creates request options for receivePaymentWebhook without sending the request
     */
    async receivePaymentWebhookRequestOpts(requestParameters: ReceivePaymentWebhookRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['webhookEvent'] == null) {
            throw new runtime.RequiredError(
                'webhookEvent',
                'Required parameter "webhookEvent" was null or undefined when calling receivePaymentWebhook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/webhooks/provider`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebhookEventToJSON(requestParameters['webhookEvent']),
        };
    }

    /**
     * Receive a payment provider callback
     */
    async receivePaymentWebhookRaw(requestParameters: ReceivePaymentWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.receivePaymentWebhookRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Receive a payment provider callback
     */
    async receivePaymentWebhook(requestParameters: ReceivePaymentWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.receivePaymentWebhookRaw(requestParameters, initOverrides);
    }

}
