// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Catalog Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package catalogserver

import (
	"context"
	"net/http"
)



// ProductsAPIRouter defines the required methods for binding the api requests to a responses for the ProductsAPI
// The ProductsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a ProductsAPIServicer to perform the required actions, then write the service results to the http response.
type ProductsAPIRouter interface { 
	ListProducts(http.ResponseWriter, *http.Request)
}


// ProductsAPIServicer defines the api actions for the ProductsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ProductsAPIServicer interface { 
	ListProducts(context.Context, int32, int32) (ImplResponse, error)
}
