// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payment Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package paymentserver

import (
	"context"
	"net/http"
)



// PaymentsAPIRouter defines the required methods for binding the api requests to a responses for the PaymentsAPI
// The PaymentsAPIRouter implementation should parse necessary information from the http request,
// pass the data to a PaymentsAPIServicer to perform the required actions, then write the service results to the http response.
type PaymentsAPIRouter interface { 
	CreatePayment(http.ResponseWriter, *http.Request)
}
// WebhooksAPIRouter defines the required methods for binding the api requests to a responses for the WebhooksAPI
// The WebhooksAPIRouter implementation should parse necessary information from the http request,
// pass the data to a WebhooksAPIServicer to perform the required actions, then write the service results to the http response.
type WebhooksAPIRouter interface { 
	ReceivePaymentWebhook(http.ResponseWriter, *http.Request)
}


// PaymentsAPIServicer defines the api actions for the PaymentsAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type PaymentsAPIServicer interface { 
	CreatePayment(context.Context, string, PaymentRequest) (ImplResponse, error)
}


// WebhooksAPIServicer defines the api actions for the WebhooksAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type WebhooksAPIServicer interface { 
	ReceivePaymentWebhook(context.Context, WebhookEvent) (ImplResponse, error)
}
