// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Order Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package orderserver

import (
	"context"
	"net/http"
)



// OrdersAPIRouter defines the required methods for binding the api requests to a responses for the OrdersAPI
// The OrdersAPIRouter implementation should parse necessary information from the http request,
// pass the data to a OrdersAPIServicer to perform the required actions, then write the service results to the http response.
type OrdersAPIRouter interface { 
	GetCart(http.ResponseWriter, *http.Request)
	CheckoutCart(http.ResponseWriter, *http.Request)
	ListOrders(http.ResponseWriter, *http.Request)
}


// OrdersAPIServicer defines the api actions for the OrdersAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type OrdersAPIServicer interface { 
	GetCart(context.Context) (ImplResponse, error)
	CheckoutCart(context.Context, string) (ImplResponse, error)
	ListOrders(context.Context, int32, int32) (ImplResponse, error)
}
