// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Catalog Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package catalogserver

import (
	"net/http"
	"strings"
)

// ProductsAPIController binds http requests to an api service and writes the service results to the http response
type ProductsAPIController struct {
	service ProductsAPIServicer
	errorHandler ErrorHandler
}

// ProductsAPIOption for how the controller is set up.
type ProductsAPIOption func(*ProductsAPIController)

// WithProductsAPIErrorHandler inject ErrorHandler into controller
func WithProductsAPIErrorHandler(h ErrorHandler) ProductsAPIOption {
	return func(c *ProductsAPIController) {
		c.errorHandler = h
	}
}

// NewProductsAPIController creates a default api controller
func NewProductsAPIController(s ProductsAPIServicer, opts ...ProductsAPIOption) *ProductsAPIController {
	controller := &ProductsAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the ProductsAPIController
func (c *ProductsAPIController) Routes() Routes {
	return Routes{
		"ListProducts": Route{
			"ListProducts",
			strings.ToUpper("Get"),
			"/api/catalog/products",
			c.ListProducts,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the ProductsAPIController
func (c *ProductsAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"ListProducts",
			strings.ToUpper("Get"),
			"/api/catalog/products",
			c.ListProducts,
		},
	}
}



// ListProducts - List products
func (c *ProductsAPIController) ListProducts(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var pageParam int32
	if query.Has("page") {
		param, err := parseNumericParameter[int32](
			query.Get("page"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "page", Err: err}, nil)
			return
		}

		pageParam = param
	} else {
		var param int32 = 1
		pageParam = param
	}
	var limitParam int32
	if query.Has("limit") {
		param, err := parseNumericParameter[int32](
			query.Get("limit"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
			WithMaximum[int32](100),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "limit", Err: err}, nil)
			return
		}

		limitParam = param
	} else {
		var param int32 = 20
		limitParam = param
	}
	result, err := c.service.ListProducts(r.Context(), pageParam, limitParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
