// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payment Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package paymentserver

import (
	"encoding/json"
	"errors"
	"net/http"
	"strings"
)

// PaymentsAPIController binds http requests to an api service and writes the service results to the http response
type PaymentsAPIController struct {
	service PaymentsAPIServicer
	errorHandler ErrorHandler
}

// PaymentsAPIOption for how the controller is set up.
type PaymentsAPIOption func(*PaymentsAPIController)

// WithPaymentsAPIErrorHandler inject ErrorHandler into controller
func WithPaymentsAPIErrorHandler(h ErrorHandler) PaymentsAPIOption {
	return func(c *PaymentsAPIController) {
		c.errorHandler = h
	}
}

// NewPaymentsAPIController creates a default api controller
func NewPaymentsAPIController(s PaymentsAPIServicer, opts ...PaymentsAPIOption) *PaymentsAPIController {
	controller := &PaymentsAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the PaymentsAPIController
func (c *PaymentsAPIController) Routes() Routes {
	return Routes{
		"CreatePayment": Route{
			"CreatePayment",
			strings.ToUpper("Post"),
			"/api/payment/payments",
			c.CreatePayment,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the PaymentsAPIController
func (c *PaymentsAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"CreatePayment",
			strings.ToUpper("Post"),
			"/api/payment/payments",
			c.CreatePayment,
		},
	}
}



// CreatePayment - Create a payment for an order
func (c *PaymentsAPIController) CreatePayment(w http.ResponseWriter, r *http.Request) {
	idempotencyKeyParam := r.Header.Get("Idempotency-Key")
	var paymentRequestParam PaymentRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&paymentRequestParam); err != nil {
		var requiredErr *RequiredError
		if errors.As(err, &requiredErr) {
			c.errorHandler(w, r, err, nil)
			return
		}
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertPaymentRequestRequired(paymentRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertPaymentRequestConstraints(paymentRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.CreatePayment(r.Context(), idempotencyKeyParam, paymentRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
