// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payment Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package paymentserver

import (
	"encoding/json"
	"errors"
	"net/http"
	"strings"
)

// WebhooksAPIController binds http requests to an api service and writes the service results to the http response
type WebhooksAPIController struct {
	service WebhooksAPIServicer
	errorHandler ErrorHandler
}

// WebhooksAPIOption for how the controller is set up.
type WebhooksAPIOption func(*WebhooksAPIController)

// WithWebhooksAPIErrorHandler inject ErrorHandler into controller
func WithWebhooksAPIErrorHandler(h ErrorHandler) WebhooksAPIOption {
	return func(c *WebhooksAPIController) {
		c.errorHandler = h
	}
}

// NewWebhooksAPIController creates a default api controller
func NewWebhooksAPIController(s WebhooksAPIServicer, opts ...WebhooksAPIOption) *WebhooksAPIController {
	controller := &WebhooksAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the WebhooksAPIController
func (c *WebhooksAPIController) Routes() Routes {
	return Routes{
		"ReceivePaymentWebhook": Route{
			"ReceivePaymentWebhook",
			strings.ToUpper("Post"),
			"/api/payment/webhooks/provider",
			c.ReceivePaymentWebhook,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the WebhooksAPIController
func (c *WebhooksAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"ReceivePaymentWebhook",
			strings.ToUpper("Post"),
			"/api/payment/webhooks/provider",
			c.ReceivePaymentWebhook,
		},
	}
}



// ReceivePaymentWebhook - Receive a payment provider callback
func (c *WebhooksAPIController) ReceivePaymentWebhook(w http.ResponseWriter, r *http.Request) {
	var webhookEventParam WebhookEvent
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&webhookEventParam); err != nil {
		var requiredErr *RequiredError
		if errors.As(err, &requiredErr) {
			c.errorHandler(w, r, err, nil)
			return
		}
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertWebhookEventRequired(webhookEventParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertWebhookEventConstraints(webhookEventParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.ReceivePaymentWebhook(r.Context(), webhookEventParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
