// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Auth Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package authserver

import (
	"context"
	"net/http"
	"errors"
)

// AuthAPIService is a service that implements the logic for the AuthAPIServicer
// This service should implement the business logic for every endpoint for the AuthAPI API.
// Include any external packages or services that will be required by this service.
type AuthAPIService struct {
}

// NewAuthAPIService creates a default api service
func NewAuthAPIService() *AuthAPIService {
	return &AuthAPIService{}
}

// Login - Authenticate user and issue tokens
func (s *AuthAPIService) Login(ctx context.Context, loginRequest LoginRequest) (ImplResponse, error) {
	// TODO - update Login with the required logic for this service method.
	// Add api_auth_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Token{}) or use other options such as http.Ok ...
	// return Response(200, Token{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Login method not implemented")
}

// RegisterUser - Register a new user
func (s *AuthAPIService) RegisterUser(ctx context.Context, registerRequest RegisterRequest) (ImplResponse, error) {
	// TODO - update RegisterUser with the required logic for this service method.
	// Add api_auth_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, User{}) or use other options such as http.Ok ...
	// return Response(201, User{}), nil

	// TODO: Uncomment the next line to return response Response(409, Error{}) or use other options such as http.Ok ...
	// return Response(409, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RegisterUser method not implemented")
}

// GetCurrentUser - Get the authenticated user profile
func (s *AuthAPIService) GetCurrentUser(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetCurrentUser with the required logic for this service method.
	// Add api_auth_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, User{}) or use other options such as http.Ok ...
	// return Response(200, User{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetCurrentUser method not implemented")
}
