// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Order Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package orderserver

import (
	"context"
	"net/http"
	"errors"
)

// OrdersAPIService is a service that implements the logic for the OrdersAPIServicer
// This service should implement the business logic for every endpoint for the OrdersAPI API.
// Include any external packages or services that will be required by this service.
type OrdersAPIService struct {
}

// NewOrdersAPIService creates a default api service
func NewOrdersAPIService() *OrdersAPIService {
	return &OrdersAPIService{}
}

// GetCart - Get the current shopping cart
func (s *OrdersAPIService) GetCart(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetCart with the required logic for this service method.
	// Add api_orders_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Cart{}) or use other options such as http.Ok ...
	// return Response(200, Cart{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetCart method not implemented")
}

// CheckoutCart - Convert the current cart into an order
func (s *OrdersAPIService) CheckoutCart(ctx context.Context, idempotencyKey string) (ImplResponse, error) {
	// TODO - update CheckoutCart with the required logic for this service method.
	// Add api_orders_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Order{}) or use other options such as http.Ok ...
	// return Response(201, Order{}), nil

	// TODO: Uncomment the next line to return response Response(409, Error{}) or use other options such as http.Ok ...
	// return Response(409, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CheckoutCart method not implemented")
}

// ListOrders - List orders for the current user
func (s *OrdersAPIService) ListOrders(ctx context.Context, page int32, limit int32) (ImplResponse, error) {
	// TODO - update ListOrders with the required logic for this service method.
	// Add api_orders_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, OrderPage{}) or use other options such as http.Ok ...
	// return Response(200, OrderPage{}), nil

	// TODO: Uncomment the next line to return response Response(401, Error{}) or use other options such as http.Ok ...
	// return Response(401, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListOrders method not implemented")
}
