// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Auth Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package authserver

import (
	"encoding/json"
	"errors"
	"net/http"
	"strings"
)

// AuthAPIController binds http requests to an api service and writes the service results to the http response
type AuthAPIController struct {
	service AuthAPIServicer
	errorHandler ErrorHandler
}

// AuthAPIOption for how the controller is set up.
type AuthAPIOption func(*AuthAPIController)

// WithAuthAPIErrorHandler inject ErrorHandler into controller
func WithAuthAPIErrorHandler(h ErrorHandler) AuthAPIOption {
	return func(c *AuthAPIController) {
		c.errorHandler = h
	}
}

// NewAuthAPIController creates a default api controller
func NewAuthAPIController(s AuthAPIServicer, opts ...AuthAPIOption) *AuthAPIController {
	controller := &AuthAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the AuthAPIController
func (c *AuthAPIController) Routes() Routes {
	return Routes{
		"Login": Route{
			"Login",
			strings.ToUpper("Post"),
			"/api/auth/login",
			c.Login,
		},
		"RegisterUser": Route{
			"RegisterUser",
			strings.ToUpper("Post"),
			"/api/auth/register",
			c.RegisterUser,
		},
		"GetCurrentUser": Route{
			"GetCurrentUser",
			strings.ToUpper("Get"),
			"/api/auth/me",
			c.GetCurrentUser,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the AuthAPIController
func (c *AuthAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"Login",
			strings.ToUpper("Post"),
			"/api/auth/login",
			c.Login,
		},
		Route{
			"RegisterUser",
			strings.ToUpper("Post"),
			"/api/auth/register",
			c.RegisterUser,
		},
		Route{
			"GetCurrentUser",
			strings.ToUpper("Get"),
			"/api/auth/me",
			c.GetCurrentUser,
		},
	}
}



// Login - Authenticate user and issue tokens
func (c *AuthAPIController) Login(w http.ResponseWriter, r *http.Request) {
	var loginRequestParam LoginRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&loginRequestParam); err != nil {
		var requiredErr *RequiredError
		if errors.As(err, &requiredErr) {
			c.errorHandler(w, r, err, nil)
			return
		}
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertLoginRequestRequired(loginRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertLoginRequestConstraints(loginRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.Login(r.Context(), loginRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// RegisterUser - Register a new user
func (c *AuthAPIController) RegisterUser(w http.ResponseWriter, r *http.Request) {
	var registerRequestParam RegisterRequest
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&registerRequestParam); err != nil {
		var requiredErr *RequiredError
		if errors.As(err, &requiredErr) {
			c.errorHandler(w, r, err, nil)
			return
		}
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertRegisterRequestRequired(registerRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertRegisterRequestConstraints(registerRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.RegisterUser(r.Context(), registerRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// GetCurrentUser - Get the authenticated user profile
func (c *AuthAPIController) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetCurrentUser(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
