// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Search Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package searchserver

import (
	"context"
	"net/http"
	"errors"
)

// SearchAPIService is a service that implements the logic for the SearchAPIServicer
// This service should implement the business logic for every endpoint for the SearchAPI API.
// Include any external packages or services that will be required by this service.
type SearchAPIService struct {
}

// NewSearchAPIService creates a default api service
func NewSearchAPIService() *SearchAPIService {
	return &SearchAPIService{}
}

// SearchProducts - Search products with filters and sorting
func (s *SearchAPIService) SearchProducts(ctx context.Context, q string, page int32, limit int32, category string, sort string) (ImplResponse, error) {
	// TODO - update SearchProducts with the required logic for this service method.
	// Add api_search_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, SearchResult{}) or use other options such as http.Ok ...
	// return Response(200, SearchResult{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SearchProducts method not implemented")
}
