// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payment Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package paymentserver

import (
	"context"
	"net/http"
	"errors"
)

// WebhooksAPIService is a service that implements the logic for the WebhooksAPIServicer
// This service should implement the business logic for every endpoint for the WebhooksAPI API.
// Include any external packages or services that will be required by this service.
type WebhooksAPIService struct {
}

// NewWebhooksAPIService creates a default api service
func NewWebhooksAPIService() *WebhooksAPIService {
	return &WebhooksAPIService{}
}

// ReceivePaymentWebhook - Receive a payment provider callback
func (s *WebhooksAPIService) ReceivePaymentWebhook(ctx context.Context, webhookEvent WebhookEvent) (ImplResponse, error) {
	// TODO - update ReceivePaymentWebhook with the required logic for this service method.
	// Add api_webhooks_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	// return Response(204, nil),nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ReceivePaymentWebhook method not implemented")
}
