// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Order Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package orderserver

import (
	"net/http"
	"strings"
)

// OrdersAPIController binds http requests to an api service and writes the service results to the http response
type OrdersAPIController struct {
	service OrdersAPIServicer
	errorHandler ErrorHandler
}

// OrdersAPIOption for how the controller is set up.
type OrdersAPIOption func(*OrdersAPIController)

// WithOrdersAPIErrorHandler inject ErrorHandler into controller
func WithOrdersAPIErrorHandler(h ErrorHandler) OrdersAPIOption {
	return func(c *OrdersAPIController) {
		c.errorHandler = h
	}
}

// NewOrdersAPIController creates a default api controller
func NewOrdersAPIController(s OrdersAPIServicer, opts ...OrdersAPIOption) *OrdersAPIController {
	controller := &OrdersAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the OrdersAPIController
func (c *OrdersAPIController) Routes() Routes {
	return Routes{
		"GetCart": Route{
			"GetCart",
			strings.ToUpper("Get"),
			"/api/order/cart",
			c.GetCart,
		},
		"CheckoutCart": Route{
			"CheckoutCart",
			strings.ToUpper("Post"),
			"/api/order/cart",
			c.CheckoutCart,
		},
		"ListOrders": Route{
			"ListOrders",
			strings.ToUpper("Get"),
			"/api/order/orders",
			c.ListOrders,
		},
	}
}

// OrderedRoutes returns all the api routes in a deterministic order for the OrdersAPIController
func (c *OrdersAPIController) OrderedRoutes() []Route {
	return []Route{
		Route{
			"GetCart",
			strings.ToUpper("Get"),
			"/api/order/cart",
			c.GetCart,
		},
		Route{
			"CheckoutCart",
			strings.ToUpper("Post"),
			"/api/order/cart",
			c.CheckoutCart,
		},
		Route{
			"ListOrders",
			strings.ToUpper("Get"),
			"/api/order/orders",
			c.ListOrders,
		},
	}
}



// GetCart - Get the current shopping cart
func (c *OrdersAPIController) GetCart(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetCart(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// CheckoutCart - Convert the current cart into an order
func (c *OrdersAPIController) CheckoutCart(w http.ResponseWriter, r *http.Request) {
	idempotencyKeyParam := r.Header.Get("Idempotency-Key")
	result, err := c.service.CheckoutCart(r.Context(), idempotencyKeyParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}

// ListOrders - List orders for the current user
func (c *OrdersAPIController) ListOrders(w http.ResponseWriter, r *http.Request) {
	query, err := parseQuery(r.URL.RawQuery)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	var pageParam int32
	if query.Has("page") {
		param, err := parseNumericParameter[int32](
			query.Get("page"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "page", Err: err}, nil)
			return
		}

		pageParam = param
	} else {
		var param int32 = 1
		pageParam = param
	}
	var limitParam int32
	if query.Has("limit") {
		param, err := parseNumericParameter[int32](
			query.Get("limit"),
			WithParse[int32](parseInt32),
			WithMinimum[int32](1),
			WithMaximum[int32](100),
		)
		if err != nil {
			c.errorHandler(w, r, &ParsingError{Param: "limit", Err: err}, nil)
			return
		}

		limitParam = param
	} else {
		var param int32 = 20
		limitParam = param
	}
	result, err := c.service.ListOrders(r.Context(), pageParam, limitParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
