// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Catalog Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package catalogserver

import (
	"context"
	"net/http"
	"errors"
)

// ProductsAPIService is a service that implements the logic for the ProductsAPIServicer
// This service should implement the business logic for every endpoint for the ProductsAPI API.
// Include any external packages or services that will be required by this service.
type ProductsAPIService struct {
}

// NewProductsAPIService creates a default api service
func NewProductsAPIService() *ProductsAPIService {
	return &ProductsAPIService{}
}

// ListProducts - List products
func (s *ProductsAPIService) ListProducts(ctx context.Context, page int32, limit int32) (ImplResponse, error) {
	// TODO - update ListProducts with the required logic for this service method.
	// Add api_products_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, ProductPage{}) or use other options such as http.Ok ...
	// return Response(200, ProductPage{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ListProducts method not implemented")
}
