// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payment Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package paymentserver

import (
	"context"
	"net/http"
	"errors"
)

// PaymentsAPIService is a service that implements the logic for the PaymentsAPIServicer
// This service should implement the business logic for every endpoint for the PaymentsAPI API.
// Include any external packages or services that will be required by this service.
type PaymentsAPIService struct {
}

// NewPaymentsAPIService creates a default api service
func NewPaymentsAPIService() *PaymentsAPIService {
	return &PaymentsAPIService{}
}

// CreatePayment - Create a payment for an order
func (s *PaymentsAPIService) CreatePayment(ctx context.Context, idempotencyKey string, paymentRequest PaymentRequest) (ImplResponse, error) {
	// TODO - update CreatePayment with the required logic for this service method.
	// Add api_payments_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Payment{}) or use other options such as http.Ok ...
	// return Response(201, Payment{}), nil

	// TODO: Uncomment the next line to return response Response(400, Error{}) or use other options such as http.Ok ...
	// return Response(400, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreatePayment method not implemented")
}
