// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Order Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package orderserver


import (
	"errors"
	"encoding/json"
	"fmt"
)



type CartItem struct {

	ProductId string `json:"productId"`

	Quantity int32 `json:"quantity"`

	UnitPrice Money `json:"unitPrice"`
}
// UnmarshalJSON validates required property keys then unmarshals into CartItem
func (o *CartItem) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"productId",
		"quantity",
		"unitPrice",
	}

	requiredNullableProperties := map[string]bool{
		"productId": false,
		"quantity": false,
		"unitPrice": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"productId": {},
		"quantity": {},
		"unitPrice": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded CartItem

	if value, exists := allProperties["productId"]; exists {
		if err = json.Unmarshal(value, &decoded.ProductId); err != nil {
			return err
		}
	}
	if value, exists := allProperties["quantity"]; exists {
		if err = json.Unmarshal(value, &decoded.Quantity); err != nil {
			return err
		}
	}
	if value, exists := allProperties["unitPrice"]; exists {
		if err = json.Unmarshal(value, &decoded.UnitPrice); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertCartItemRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertCartItemRequired(obj CartItem) error {
	elements := map[string]interface{}{
		"unitPrice": obj.UnitPrice,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertMoneyRequired(obj.UnitPrice); err != nil {
		return err
	}
	return nil
}

// AssertCartItemConstraints checks if the values respects the defined constraints
func AssertCartItemConstraints(obj CartItem) error {
	if obj.Quantity < 1 {
		return &ParsingError{Param: "Quantity", Err: errors.New(errMsgMinValueConstraint)}
	}
	if err := AssertMoneyConstraints(obj.UnitPrice); err != nil {
		return err
	}
	return nil
}
