// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Auth Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package authserver


import (
	"encoding/json"
	"fmt"
)



type LoginRequest struct {

	Email string `json:"email"`

	Password string `json:"password"`
}
// UnmarshalJSON validates required property keys then unmarshals into LoginRequest
func (o *LoginRequest) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"email",
		"password",
	}

	requiredNullableProperties := map[string]bool{
		"email": false,
		"password": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"email": {},
		"password": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded LoginRequest

	if value, exists := allProperties["email"]; exists {
		if err = json.Unmarshal(value, &decoded.Email); err != nil {
			return err
		}
	}
	if value, exists := allProperties["password"]; exists {
		if err = json.Unmarshal(value, &decoded.Password); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertLoginRequestRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertLoginRequestRequired(obj LoginRequest) error {
	return nil
}

// AssertLoginRequestConstraints checks if the values respects the defined constraints
func AssertLoginRequestConstraints(obj LoginRequest) error {
	return nil
}
