// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Search Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package searchserver


import (
	"encoding/json"
	"fmt"
)



type Product struct {

	Id string `json:"id"`

	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	Price Money `json:"price"`

	InventoryStatus string `json:"inventoryStatus"`
}
// UnmarshalJSON validates required property keys then unmarshals into Product
func (o *Product) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"id",
		"name",
		"price",
		"inventoryStatus",
	}

	requiredNullableProperties := map[string]bool{
		"id": false,
		"name": false,
		"price": false,
		"inventoryStatus": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"name": {},
		"description": {},
		"price": {},
		"inventoryStatus": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Product

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["name"]; exists {
		if err = json.Unmarshal(value, &decoded.Name); err != nil {
			return err
		}
	}
	if value, exists := allProperties["description"]; exists {
		if err = json.Unmarshal(value, &decoded.Description); err != nil {
			return err
		}
	}
	if value, exists := allProperties["price"]; exists {
		if err = json.Unmarshal(value, &decoded.Price); err != nil {
			return err
		}
	}
	if value, exists := allProperties["inventoryStatus"]; exists {
		if err = json.Unmarshal(value, &decoded.InventoryStatus); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertProductRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertProductRequired(obj Product) error {
	elements := map[string]interface{}{
		"price": obj.Price,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertMoneyRequired(obj.Price); err != nil {
		return err
	}
	return nil
}

// AssertProductConstraints checks if the values respects the defined constraints
func AssertProductConstraints(obj Product) error {
	if err := AssertMoneyConstraints(obj.Price); err != nil {
		return err
	}
	return nil
}
