// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Order Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package orderserver


import (
	"encoding/json"
	"fmt"
)



type Cart struct {

	Items []CartItem `json:"items"`

	Subtotal Money `json:"subtotal"`
}
// UnmarshalJSON validates required property keys then unmarshals into Cart
func (o *Cart) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"items",
		"subtotal",
	}

	requiredNullableProperties := map[string]bool{
		"items": false,
		"subtotal": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"items": {},
		"subtotal": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Cart

	if value, exists := allProperties["items"]; exists {
		if err = json.Unmarshal(value, &decoded.Items); err != nil {
			return err
		}
	}
	if value, exists := allProperties["subtotal"]; exists {
		if err = json.Unmarshal(value, &decoded.Subtotal); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertCartRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertCartRequired(obj Cart) error {
	elements := map[string]interface{}{
		"items": obj.Items,
		"subtotal": obj.Subtotal,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Items {
		if err := AssertCartItemRequired(el); err != nil {
			return err
		}
	}
	if err := AssertMoneyRequired(obj.Subtotal); err != nil {
		return err
	}
	return nil
}

// AssertCartConstraints checks if the values respects the defined constraints
func AssertCartConstraints(obj Cart) error {
	for _, el := range obj.Items {
		if err := AssertCartItemConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertMoneyConstraints(obj.Subtotal); err != nil {
		return err
	}
	return nil
}
