// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Catalog Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package catalogserver


import (
	"encoding/json"
	"fmt"
)



type ProductPage struct {

	Items []Product `json:"items"`

	Pagination Pagination `json:"pagination"`
}
// UnmarshalJSON validates required property keys then unmarshals into ProductPage
func (o *ProductPage) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"items",
		"pagination",
	}

	requiredNullableProperties := map[string]bool{
		"items": false,
		"pagination": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"items": {},
		"pagination": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded ProductPage

	if value, exists := allProperties["items"]; exists {
		if err = json.Unmarshal(value, &decoded.Items); err != nil {
			return err
		}
	}
	if value, exists := allProperties["pagination"]; exists {
		if err = json.Unmarshal(value, &decoded.Pagination); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertProductPageRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertProductPageRequired(obj ProductPage) error {
	elements := map[string]interface{}{
		"items": obj.Items,
		"pagination": obj.Pagination,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Items {
		if err := AssertProductRequired(el); err != nil {
			return err
		}
	}
	if err := AssertPaginationRequired(obj.Pagination); err != nil {
		return err
	}
	return nil
}

// AssertProductPageConstraints checks if the values respects the defined constraints
func AssertProductPageConstraints(obj ProductPage) error {
	for _, el := range obj.Items {
		if err := AssertProductConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertPaginationConstraints(obj.Pagination); err != nil {
		return err
	}
	return nil
}
