// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payment Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package paymentserver


import (
	"encoding/json"
	"fmt"
)



type WebhookEvent struct {

	EventId string `json:"eventId"`

	Type string `json:"type"`

	PaymentId string `json:"paymentId"`
}
// UnmarshalJSON validates required property keys then unmarshals into WebhookEvent
func (o *WebhookEvent) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"eventId",
		"type",
		"paymentId",
	}

	requiredNullableProperties := map[string]bool{
		"eventId": false,
		"type": false,
		"paymentId": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"eventId": {},
		"type": {},
		"paymentId": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded WebhookEvent

	if value, exists := allProperties["eventId"]; exists {
		if err = json.Unmarshal(value, &decoded.EventId); err != nil {
			return err
		}
	}
	if value, exists := allProperties["type"]; exists {
		if err = json.Unmarshal(value, &decoded.Type); err != nil {
			return err
		}
	}
	if value, exists := allProperties["paymentId"]; exists {
		if err = json.Unmarshal(value, &decoded.PaymentId); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertWebhookEventRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertWebhookEventRequired(obj WebhookEvent) error {
	return nil
}

// AssertWebhookEventConstraints checks if the values respects the defined constraints
func AssertWebhookEventConstraints(obj WebhookEvent) error {
	return nil
}
