// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Order Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package orderserver


import (
	"encoding/json"
	"fmt"
)



type Money struct {

	// Amount in the smallest currency unit.
	Amount int64 `json:"amount"`

	Currency string `json:"currency" validate:"regexp=^[A-Z]{3}$"`
}
// UnmarshalJSON validates required property keys then unmarshals into Money
func (o *Money) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"amount",
		"currency",
	}

	requiredNullableProperties := map[string]bool{
		"amount": false,
		"currency": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"amount": {},
		"currency": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Money

	if value, exists := allProperties["amount"]; exists {
		if err = json.Unmarshal(value, &decoded.Amount); err != nil {
			return err
		}
	}
	if value, exists := allProperties["currency"]; exists {
		if err = json.Unmarshal(value, &decoded.Currency); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertMoneyRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertMoneyRequired(obj Money) error {
	return nil
}

// AssertMoneyConstraints checks if the values respects the defined constraints
func AssertMoneyConstraints(obj Money) error {
	return nil
}
