// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Search Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package searchserver


import (
	"errors"
	"encoding/json"
	"fmt"
)



type Pagination struct {

	Page int32 `json:"page"`

	Limit int32 `json:"limit"`

	Total int32 `json:"total"`
}
// UnmarshalJSON validates required property keys then unmarshals into Pagination
func (o *Pagination) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"page",
		"limit",
		"total",
	}

	requiredNullableProperties := map[string]bool{
		"page": false,
		"limit": false,
		"total": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"page": {},
		"limit": {},
		"total": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Pagination

	if value, exists := allProperties["page"]; exists {
		if err = json.Unmarshal(value, &decoded.Page); err != nil {
			return err
		}
	}
	if value, exists := allProperties["limit"]; exists {
		if err = json.Unmarshal(value, &decoded.Limit); err != nil {
			return err
		}
	}
	if value, exists := allProperties["total"]; exists {
		if err = json.Unmarshal(value, &decoded.Total); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertPaginationRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertPaginationRequired(obj Pagination) error {
	return nil
}

// AssertPaginationConstraints checks if the values respects the defined constraints
func AssertPaginationConstraints(obj Pagination) error {
	if obj.Page < 1 {
		return &ParsingError{Param: "Page", Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Limit < 1 {
		return &ParsingError{Param: "Limit", Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.Limit > 100 {
		return &ParsingError{Param: "Limit", Err: errors.New(errMsgMaxValueConstraint)}
	}
	if obj.Total < 0 {
		return &ParsingError{Param: "Total", Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
