// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Auth Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package authserver


import (
	"errors"
	"encoding/json"
	"fmt"
)



type Token struct {

	AccessToken string `json:"accessToken"`

	TokenType string `json:"tokenType"`

	ExpiresIn int32 `json:"expiresIn"`
}
// UnmarshalJSON validates required property keys then unmarshals into Token
func (o *Token) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"accessToken",
		"tokenType",
		"expiresIn",
	}

	requiredNullableProperties := map[string]bool{
		"accessToken": false,
		"tokenType": false,
		"expiresIn": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"accessToken": {},
		"tokenType": {},
		"expiresIn": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Token

	if value, exists := allProperties["accessToken"]; exists {
		if err = json.Unmarshal(value, &decoded.AccessToken); err != nil {
			return err
		}
	}
	if value, exists := allProperties["tokenType"]; exists {
		if err = json.Unmarshal(value, &decoded.TokenType); err != nil {
			return err
		}
	}
	if value, exists := allProperties["expiresIn"]; exists {
		if err = json.Unmarshal(value, &decoded.ExpiresIn); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertTokenRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertTokenRequired(obj Token) error {
	return nil
}

// AssertTokenConstraints checks if the values respects the defined constraints
func AssertTokenConstraints(obj Token) error {
	if obj.ExpiresIn < 1 {
		return &ParsingError{Param: "ExpiresIn", Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
