// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Auth Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package authserver


import (
	"time"
	"encoding/json"
	"fmt"
)



type User struct {

	Id string `json:"id"`

	Email string `json:"email"`

	DisplayName string `json:"displayName"`

	CreatedAt time.Time `json:"createdAt"`
}
// UnmarshalJSON validates required property keys then unmarshals into User
func (o *User) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"id",
		"email",
		"displayName",
		"createdAt",
	}

	requiredNullableProperties := map[string]bool{
		"id": false,
		"email": false,
		"displayName": false,
		"createdAt": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"email": {},
		"displayName": {},
		"createdAt": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded User

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["email"]; exists {
		if err = json.Unmarshal(value, &decoded.Email); err != nil {
			return err
		}
	}
	if value, exists := allProperties["displayName"]; exists {
		if err = json.Unmarshal(value, &decoded.DisplayName); err != nil {
			return err
		}
	}
	if value, exists := allProperties["createdAt"]; exists {
		if err = json.Unmarshal(value, &decoded.CreatedAt); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertUserRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertUserRequired(obj User) error {
	return nil
}

// AssertUserConstraints checks if the values respects the defined constraints
func AssertUserConstraints(obj User) error {
	return nil
}
