// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Payment Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package paymentserver


import (
	"encoding/json"
	"fmt"
)



type PaymentRequest struct {

	OrderId string `json:"orderId"`

	Amount Money `json:"amount"`

	PaymentMethodToken string `json:"paymentMethodToken"`
}
// UnmarshalJSON validates required property keys then unmarshals into PaymentRequest
func (o *PaymentRequest) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"orderId",
		"amount",
		"paymentMethodToken",
	}

	requiredNullableProperties := map[string]bool{
		"orderId": false,
		"amount": false,
		"paymentMethodToken": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"orderId": {},
		"amount": {},
		"paymentMethodToken": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded PaymentRequest

	if value, exists := allProperties["orderId"]; exists {
		if err = json.Unmarshal(value, &decoded.OrderId); err != nil {
			return err
		}
	}
	if value, exists := allProperties["amount"]; exists {
		if err = json.Unmarshal(value, &decoded.Amount); err != nil {
			return err
		}
	}
	if value, exists := allProperties["paymentMethodToken"]; exists {
		if err = json.Unmarshal(value, &decoded.PaymentMethodToken); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertPaymentRequestRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertPaymentRequestRequired(obj PaymentRequest) error {
	elements := map[string]interface{}{
		"amount": obj.Amount,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertMoneyRequired(obj.Amount); err != nil {
		return err
	}
	return nil
}

// AssertPaymentRequestConstraints checks if the values respects the defined constraints
func AssertPaymentRequestConstraints(obj PaymentRequest) error {
	if err := AssertMoneyConstraints(obj.Amount); err != nil {
		return err
	}
	return nil
}
