// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Order Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package orderserver


import (
	"time"
	"encoding/json"
	"fmt"
)



type Order struct {

	Id string `json:"id"`

	Status string `json:"status"`

	Items []CartItem `json:"items"`

	Total Money `json:"total"`

	CreatedAt time.Time `json:"createdAt"`
}
// UnmarshalJSON validates required property keys then unmarshals into Order
func (o *Order) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"id",
		"status",
		"items",
		"total",
		"createdAt",
	}

	requiredNullableProperties := map[string]bool{
		"id": false,
		"status": false,
		"items": false,
		"total": false,
		"createdAt": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"id": {},
		"status": {},
		"items": {},
		"total": {},
		"createdAt": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Order

	if value, exists := allProperties["id"]; exists {
		if err = json.Unmarshal(value, &decoded.Id); err != nil {
			return err
		}
	}
	if value, exists := allProperties["status"]; exists {
		if err = json.Unmarshal(value, &decoded.Status); err != nil {
			return err
		}
	}
	if value, exists := allProperties["items"]; exists {
		if err = json.Unmarshal(value, &decoded.Items); err != nil {
			return err
		}
	}
	if value, exists := allProperties["total"]; exists {
		if err = json.Unmarshal(value, &decoded.Total); err != nil {
			return err
		}
	}
	if value, exists := allProperties["createdAt"]; exists {
		if err = json.Unmarshal(value, &decoded.CreatedAt); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertOrderRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertOrderRequired(obj Order) error {
	elements := map[string]interface{}{
		"items": obj.Items,
		"total": obj.Total,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Items {
		if err := AssertCartItemRequired(el); err != nil {
			return err
		}
	}
	if err := AssertMoneyRequired(obj.Total); err != nil {
		return err
	}
	return nil
}

// AssertOrderConstraints checks if the values respects the defined constraints
func AssertOrderConstraints(obj Order) error {
	for _, el := range obj.Items {
		if err := AssertCartItemConstraints(el); err != nil {
			return err
		}
	}
	if err := AssertMoneyConstraints(obj.Total); err != nil {
		return err
	}
	return nil
}
