// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Search Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package searchserver


import (
	"encoding/json"
	"fmt"
)



type Error struct {

	Code string `json:"code"`

	Message string `json:"message"`

	Details map[string]interface{} `json:"details,omitempty"`
}
// UnmarshalJSON validates required property keys then unmarshals into Error
func (o *Error) UnmarshalJSON(data []byte) (err error) {
	// Presence is checked against required fields that exist on this struct,
	// including fields promoted from embedded allOf parents.
	requiredProperties := []string{
		"code",
		"message",
	}

	requiredNullableProperties := map[string]bool{
		"code": false,
		"message": false,
	}

	allowedJsonKeys := map[string]struct{}{
		"code": {},
		"message": {},
		"details": {},
	}

	allProperties := make(map[string]json.RawMessage)

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		value, exists := allProperties[requiredProperty]
		if !exists {
			return &RequiredError{Field: requiredProperty}
		}
		if string(value) == "null" && !requiredNullableProperties[requiredProperty] {
			return &RequiredError{Field: requiredProperty}
		}
	}

	for key := range allProperties {
		if _, exists := allowedJsonKeys[key]; !exists {
			return fmt.Errorf("json: unknown field %q", key)
		}
	}

	var decoded Error

	if value, exists := allProperties["code"]; exists {
		if err = json.Unmarshal(value, &decoded.Code); err != nil {
			return err
		}
	}
	if value, exists := allProperties["message"]; exists {
		if err = json.Unmarshal(value, &decoded.Message); err != nil {
			return err
		}
	}
	if value, exists := allProperties["details"]; exists {
		if err = json.Unmarshal(value, &decoded.Details); err != nil {
			return err
		}
	}

	*o = decoded

	return nil
}

// AssertErrorRequired checks complex required fields (models, arrays, maps) and embedded parents.
// Primitive required fields are validated for JSON request bodies in UnmarshalJSON so zero values remain valid.
func AssertErrorRequired(obj Error) error {
	return nil
}

// AssertErrorConstraints checks if the values respects the defined constraints
func AssertErrorConstraints(obj Error) error {
	return nil
}
