type: "object"
required:
  - "id"
  - "name"
  - "price"
  - "inventoryStatus"

properties:
  id:
    type: "string"
    format: "uuid"

  name:
    type: "string"

  description:
    type: "string"

  price:
    $ref: "../../../shared/components/schemas/Money.yaml"

  inventoryStatus:
    type: "string"
    enum:
      - "in_stock"
      - "low_stock"
      - "out_of_stock"
