get:
  operationId: "listProducts"
  # prettier-ignore
  summary: |-
    List products
  security: []

  tags:
    - "Products"

  parameters:
    - $ref: "../openapi.yaml#/components/parameters/Page"
    - $ref: "../openapi.yaml#/components/parameters/Limit"
    - $ref: "../openapi.yaml#/components/parameters/Locale"
    - $ref: "../openapi.yaml#/components/parameters/Currency"

    - name: "categoryId"
      in: "query"
      required: false
      schema:
        type: "string"
        format: "uuid"

  responses:
    "200":
      # prettier-ignore
      description: |-
        Product page
      content:
        application/json:
          schema:
            $ref: "../components/schemas/ProductPage.yaml"

    "400":
      $ref: "../../shared/components/responses/BadRequest.yaml"
