/* tslint:disable */
/* eslint-disable */
/**
 * Order Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    MoneyToJSONTyped,
} from './Money';
import type { CartItem } from './CartItem';
import {
    CartItemFromJSON,
    CartItemFromJSONTyped,
    CartItemToJSON,
    CartItemToJSONTyped,
} from './CartItem';

/**
 * 
 * @export
 * @interface Cart
 */
export interface Cart {
    /**
     * 
     */
    items: Array<CartItem>;
    /**
     * 
     */
    subtotal: Money;
}

/**
 * Check if a given object implements the Cart interface.
 */
export function instanceOfCart(value: object): value is Cart {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('subtotal' in value) || value['subtotal'] === undefined) return false;
    return true;
}

export function CartFromJSON(json: any): Cart {
    return CartFromJSONTyped(json, false);
}

export function CartFromJSONTyped(json: any, ignoreDiscriminator: boolean): Cart {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(CartItemFromJSON)),
        'subtotal': MoneyFromJSON(json['subtotal']),
    };
}

export function CartToJSON(json: any): Cart {
    return CartToJSONTyped(json, false);
}

export function CartToJSONTyped(value?: Cart | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(CartItemToJSON)),
        'subtotal': MoneyToJSON(value['subtotal']),
    };
}

