/* tslint:disable */
/* eslint-disable */
/**
 * Order Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
    OrderToJSONTyped,
} from './Order';
import type { Pagination } from './Pagination';
import {
    PaginationFromJSON,
    PaginationFromJSONTyped,
    PaginationToJSON,
    PaginationToJSONTyped,
} from './Pagination';

/**
 * 
 * @export
 * @interface OrderPage
 */
export interface OrderPage {
    /**
     * 
     */
    items: Array<Order>;
    /**
     * 
     */
    pagination: Pagination;
}

/**
 * Check if a given object implements the OrderPage interface.
 */
export function instanceOfOrderPage(value: object): value is OrderPage {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function OrderPageFromJSON(json: any): OrderPage {
    return OrderPageFromJSONTyped(json, false);
}

export function OrderPageFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderPage {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(OrderFromJSON)),
        'pagination': PaginationFromJSON(json['pagination']),
    };
}

export function OrderPageToJSON(json: any): OrderPage {
    return OrderPageToJSONTyped(json, false);
}

export function OrderPageToJSONTyped(value?: OrderPage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(OrderToJSON)),
        'pagination': PaginationToJSON(value['pagination']),
    };
}

