/* tslint:disable */
/* eslint-disable */
/**
 * Payment Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Money } from './Money';
import {
    MoneyFromJSON,
    MoneyFromJSONTyped,
    MoneyToJSON,
    MoneyToJSONTyped,
} from './Money';

/**
 * 
 * @export
 * @interface PaymentRequest
 */
export interface PaymentRequest {
    /**
     * 
     */
    orderId: string;
    /**
     * 
     */
    amount: Money;
    /**
     * 
     */
    paymentMethodToken: string;
}

/**
 * Check if a given object implements the PaymentRequest interface.
 */
export function instanceOfPaymentRequest(value: object): value is PaymentRequest {
    if (!('orderId' in value) || value['orderId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('paymentMethodToken' in value) || value['paymentMethodToken'] === undefined) return false;
    return true;
}

export function PaymentRequestFromJSON(json: any): PaymentRequest {
    return PaymentRequestFromJSONTyped(json, false);
}

export function PaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['orderId'],
        'amount': MoneyFromJSON(json['amount']),
        'paymentMethodToken': json['paymentMethodToken'],
    };
}

export function PaymentRequestToJSON(json: any): PaymentRequest {
    return PaymentRequestToJSONTyped(json, false);
}

export function PaymentRequestToJSONTyped(value?: PaymentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderId': value['orderId'],
        'amount': MoneyToJSON(value['amount']),
        'paymentMethodToken': value['paymentMethodToken'],
    };
}

