/* tslint:disable */
/* eslint-disable */
/**
 * Auth Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Token
 */
export interface Token {
    /**
     * 
     */
    accessToken: string;
    /**
     * 
     */
    tokenType: TokenTokenTypeEnum;
    /**
     * 
     */
    expiresIn: number;
}


/**
 * @export
 */
export const TokenTokenTypeEnum = {
    Bearer: 'Bearer',
} as const;
export type TokenTokenTypeEnum = typeof TokenTokenTypeEnum[keyof typeof TokenTokenTypeEnum];


/**
 * Check if a given object implements the Token interface.
 */
export function instanceOfToken(value: object): value is Token {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (value['tokenType'] !== 'Bearer') return false;
    
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function TokenFromJSON(json: any): Token {
    return TokenFromJSONTyped(json, false);
}

export function TokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Token {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'tokenType': json['tokenType'],
        'expiresIn': json['expiresIn'],
    };
}

export function TokenToJSON(json: any): Token {
    return TokenToJSONTyped(json, false);
}

export function TokenToJSONTyped(value?: Token | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
        'tokenType': value['tokenType'],
        'expiresIn': value['expiresIn'],
    };
}

