/* tslint:disable */
/* eslint-disable */
/**
 * Payment Service API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookEvent
 */
export interface WebhookEvent {
    /**
     * 
     */
    eventId: string;
    /**
     * 
     */
    type: WebhookEventTypeEnum;
    /**
     * 
     */
    paymentId: string;
}


/**
 * @export
 */
export const WebhookEventTypeEnum = {
    PaymentAuthorized: 'payment.authorized',
    PaymentCaptured: 'payment.captured',
    PaymentFailed: 'payment.failed',
} as const;
export type WebhookEventTypeEnum = typeof WebhookEventTypeEnum[keyof typeof WebhookEventTypeEnum];


/**
 * Check if a given object implements the WebhookEvent interface.
 */
export function instanceOfWebhookEvent(value: object): value is WebhookEvent {
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('paymentId' in value) || value['paymentId'] === undefined) return false;
    return true;
}

export function WebhookEventFromJSON(json: any): WebhookEvent {
    return WebhookEventFromJSONTyped(json, false);
}

export function WebhookEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEvent {
    if (json == null) {
        return json;
    }
    return {
        
        'eventId': json['eventId'],
        'type': json['type'],
        'paymentId': json['paymentId'],
    };
}

export function WebhookEventToJSON(json: any): WebhookEvent {
    return WebhookEventToJSONTyped(json, false);
}

export function WebhookEventToJSONTyped(value?: WebhookEvent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'eventId': value['eventId'],
        'type': value['type'],
        'paymentId': value['paymentId'],
    };
}

